version: '3.9'

services:
  app:
    image: node:20
    container_name: adonis-container
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '9229:9229' # Expose debugging port
      - '3333:3333' # Expose AdonisJS port
    depends_on:
      - postgres # Ensure the Postgres container starts first
    command: >
      bash -c "npm install &&
               node ace migration:run &&
               npm run debug"

  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432' # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity
    ports:
      - '9200:9200'

volumes:
  postgres_data:
